server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway

  cloud:
    gateway:
      routes:
        - id: 163_route
          uri: https://www.163.com/
          filters:
            - AddRequestHeader=X-Request-Foo, Bar1
          predicates:
            - Path=/163
        - id: baidu_route
          uri: https://www.baidu.com/
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - Path=/cache/**
        - id: ecs_route
          uri: http://xxx.xxx.com/
          predicates:
            - Path=/ecs/**
        - id: rds_route
          uri: http://xxx.xxx.com/
          predicates:
            - Path=/rds/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO

## 服务发现注册配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
